### ISSUE TITLE
Using sudosh with central user management (LDAP)

### ISSUE THREAD

**Issue by cmonty14** [cloudposse/sudosh#10]
Hello!
Can I utilize this tool with central user management (LDAP) instead of local user management?
If yes, what would you recommend for the implementation then?

THX

**Comment by osterman** [comment]
I believe it should work find with LDAP user management. Just make sure that the user's shell is configured to `/usr/bin/sudosh` (or where ever you install it). 

Also, make sure to follow the setup procedures:
https://github.com/cloudposse/sudosh#usage
