### ISSUE TITLE
Clarification on how to securely utilize sudosh

### ISSUE THREAD

**Issue by mzpqnxow** [cloudposse/sudosh#13]
Hello devs,

I wanted to just point out something that you may know, but that users may not. For complete and secure logging, it is not sufficient to simply set the user shell to `sudosh`. You **must** either use `ForceCommand` or a bastion that **disallows users from invoking SSH directly**. Otherwise you have the issue of the following session on `somehost` going (partially) unaudited:

`$ ssh user@somehost bash`

In this case, even though the user's shell may be set to `sudosh`, the only things that will be audited are the initial invocation of bash and the stdout/stderr of the bash shell that was invoked. The stdin of the bash session will not be logged, based on my (limited) testing. Apologies if I made a mistake in testing, but this is what it looks like to me

References to `ForceCommand` and a bastion host are made in the documentation, but I feel that the documentation doesn't do a great job in pointing out this "bypass" (albeit partial) of session logging.

Maybe I am just not reading the README carefully enough, but it seems like this specific case should be called out as a common pitfall as I think a lot of system administrators overlook things like this, unless they have experience in doing basic subversion testing

Feel free to close this with comments if you feel that this is common knowledge and not a risk. Alternately, maybe you can update the README, or invite a PR to improve the README. I just wanted to make sure there was awareness around this common mistake that syadmins tend to make. I've seen this sort of mistake in several environments, not with `sudosh`, but with similar tools

Thanks

**Comment by osterman** [comment]
@mzpqnxow thanks for taking the time to post.

> You **must** either use `ForceCommand` or a bastion that **disallows users from invoking SSH directly**

The `README.md` specifically calls out that `ForceCommand` **should not** be relied on. This is discussed in [some detail](http://serverfault.com/a/639814) and linked in the `README`. The `ForceCommand` is so often misrepresented as a security mechanism, but it really is not. We recommend that the `/etc/shells` controls the valid login shells, so if `bash` is not a valid login shell, it should not be possible to bypass.

**Comment by timp87** [comment]
No matter what is in /etc/shells @mzpqnxow 's case will work.
Yes, it will be uncomfortable for a user who try it, but still possible and an Administrator won't see what was actually typed by the user. Only stdout/stderr of the shell (not ttyout).

Possibly may be workarounded by disabling non-interactive shell (via ForceCommand?)
Or setting sudoers to log not only log_output

It would be great if sshd had an option to forcibly allocate a pty no matter what client wanted.
But unfortunately only ssh (client) has this ability with -t (-tt) now.

**Comment by osterman** [comment]
>  Only stdout/stderr of the shell (not ttyout). 

This is not accurate. The full `tty` session is recorded. E.g. if you drop in to `vim` everything that was typed or output is indeed recorded. I was really impressed by this actually, which is what led us to initially invest in this tool

> disabling non-interactive shell (via ForceCommand?)

The `ForceCommand` is a redherring. It's the easiest of all mechanisms to bypass.

http://serverfault.com/a/639814

> but still possible and an Administrator won't see what was actually typed by the user.

It's highly probable that the user can disable echo of tty input (e.g. like when using `passwd`), but the attempt of disabling input would be recorded.

> You must either use ForceCommand or a bastion that disallows users from invoking SSH directly. 

Let me qualify "invoking SSSH directly": It's essential to disable SSH tunneling, or else all that will get recorded is an encrypted SSH session.  

If the user runs "ssh" (e.g. directly) from inside one recorded session via a bastion, then that will get recorded in clear text.

 
> No matter what is in /etc/shells @mzpqnxow 's case will work.

Maybe that's the case. Pretty sure we tested this back in the day with `cloudposse/bastion` and were not able to bypass. However, we might have done other things as well to make that happen. 

See example here: https://github.com/cloudposse/bastion


-------

Anyways, for anyone really serious session logging there's really only one option: https://github.com/gravitational/teleport

**Comment by timp87** [comment]
@osterman looks like you don't fully understand what @mzpqnxow and I wanted to say.
Your tools is fine. It's very useful.
`ForceCommand` is misleading.
You're saying right things.

But we were talking about particular case that @mzpqnxow pointed to:
`$ ssh user@somehost bash`
Please reread all the thread. Then try it out and see what actually recorded.

**Comment by osterman** [comment]
I am not able to circumvent `sudosh` capturing input/output using the aforementioned circumvention. 

```
$ ssh user@somehost bash
```

Please see the screen recording.

[![image](https://user-images.githubusercontent.com/52489/61086558-0568b880-a3e8-11e9-82a5-3d727f974b0e.png)](https://embed.vidyard.com/share/K6uuYRuQChf7Wu7cccQoy1?)

**Comment by timp87** [comment]
@osterman you was not able cause you hadn't followed what I want you to see.
You run
`$ ssh user@somehost bash -c 'blabla'`
I wanted you to run literally
`$ ssh user@somehost bash`
no other arguments to this command.

Once again, you won't fully bypass recording. What will be hided is user input. Not output.
I know there are a lot of other ways to do the same like `stty -echo`, etc.

@mzpqnxow the only workaround I found so far is to deny sessions without allocated tty with sudoers config `requiretty`.

**Comment by osterman** [comment]
@mzpqnxow correct, the best recommendation is to use `requiretty`. 

Either globally:
```
Defaults requiretty
```
Or per user:
```
Defaults erik:requiretty
```

I'll update the docs with this recommendation.

**Comment by osterman** [comment]
@mzpqnxow please see #14. Anything you'd like to add?

**Comment by mzpqnxow** [comment]
I think that's a great improvement and don't have anything to add at this time. Sometimes it is taken for granted how much sysadmins know about these sort of things so those caveats are a really valuable addition to the README. Thanks for taking this into consideration and adding it to the documentation!
